### ISSUE TITLE
Would you mind publishing trained weights?

### ISSUE THREAD

**Issue by mahaveer0suthar** [SIAnalytics/dual-hrnet#1]
Would you mind publishing trained weights?

**Comment by jamesKoo** [comment]
I will upload trained weights files soon.

**Comment by jamesKoo** [comment]
Add trained model weight into README.md
link: https://drive.google.com/file/d/1wB8I8zw9tQ8adiBBGS5wdHBh2XGf9bck/view?usp=sharing
